// majed-nuxt/app/components/ui/progress/Progress.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
const props = defineProps<{ value?: number; class?: string }>()
</script>
<template>
  <div :class="cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', $props.class)">
    <div class="h-full bg-primary transition-all" :style="{ width: `${Math.max(0, Math.min(100, value ?? 0))}%` }" />
  </div>
</template>

// src/components/ui/progress.tsx
"use client";

import * as React from "react";
import * as ProgressPrimitive from "@radix-ui/react-progress";

import { cn } from "@/lib/utils";

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn("relative h-2 w-full overflow-hidden rounded-full bg-primary/20", className)}
    {...props}
  >
    {/* RTL-aware fill: anchored to inline-start, grows by width. Works in both LTR and RTL. */}
    <ProgressPrimitive.Indicator
      className="h-full bg-primary transition-all rounded-full"
      style={{ width: `${Math.min(100, Math.max(0, value || 0))}%` }}
    />
  </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
